services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: z_ddt_postgres_dev
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${POSTGRES_PORT_DEV}:5432"
    volumes:
      - ./docker/postgres/dev_data:/var/lib/postgresql/data
    networks:
      - ddt_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-dev:
    container_name: z_ddt_api_dev
    build:
      context: ./csharp
      dockerfile: api/Dockerfile.dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres-dev;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "${CSHARP_PORT_DEV}:8080"
    volumes:
      - ./csharp:/app
      - /app/api/obj
      - /app/api/bin
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - ddt_net

networks:
  ddt_net:
    driver: bridge
