name: Backend CI/CD

on:
  push:
    branches: ["master"]
    paths:
      - "csharp/**"
      - ".github/workflows/csharp_deploy.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "csharp/**"
      - ".github/workflows/csharp_deploy.yml"

env:
  REGISTRY: ghcr.io
  API_NAME: KlaudiuszSoltysik/district-digital-twin/api
  WEBSITE_NAME: KlaudiuszSoltysik/district-digital-twin/website

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - run: dotnet test csharp/csharp.sln

  build-and-push:
    name: Build and push image
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push API image
      - name: Extract metadata for API
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./csharp
          file: ./csharp/api/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      # Build and push website image
      - name: Extract metadata for website
        id: meta-website
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.WEBSITE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push website
        uses: docker/build-push-action@v5
        with:
          context: ./csharp
          file: ./csharp/website/Dockerfile
          push: true
          tags: ${{ steps.meta-website.outputs.tags }}
          labels: ${{ steps.meta-website.outputs.labels }}

      # Generate and commit documentation
      - name: Setup .NET for docs generation
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Generate documentation
        run: dotnet build csharp/api/api.csproj -c Release

      - name: Commit and push documentation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: automatic api documentation update [skip ci]"
          file_pattern: csharp/api/api_documentation.json
          branch: refs/heads/master
          push_options: "--force"
