# name: Python Tests
#
# on:
#   push:
#     branches: ["master"]
#     paths:
#       - "python/**"
#       - ".github/workflows/python_tests.yml"
#   pull_request:
#     branches: ["master"]
#     paths:
#       - "python/**"
#       - ".github/workflows/python_tests.yml"
#
# jobs:
#   test:
#     runs-on: ubuntu-latest
#
#     steps:
#       - uses: actions/checkout@v3
#
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.12"
#
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r python/requirements.txt
#
#       - name: Run tests with pytest
#         run: |
#           PYTHONPATH=python pytest python/tests/tests_main.py
